project:
  type: website
  output-dir: .quarto/_site
  preview:
    port: 4200

website:
  title: "Filecoin Data Portal"
  favicon: "logo.svg"
  repo-url: https://github.com/davidgasquez/filecoin-data-portal
  open-graph: true
  twitter-card: true
  site-url: https://filecoindataportal.xyz/
  search: false
  navbar:
    logo: logo.svg
    pinned: false
    left:
      - text: "Data"
        href: data.html
      - text: "Dashboards"
        href: dashboards.html
      - text: "Sources"
        href: docs/data-sources.html
      - text: "Quickstart"
        href: docs/using-datasets.html
    right:
      - text: "About"
        href: about.html
      - text: "Request Dataset"
        href: https://github.com/davidgasquez/filecoin-data-portal/issues/new
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez/
      - icon: github
        href: https://github.com/davidgasquez/filecoin-data-portal

format:
  html:
    theme: cosmo
    toc: true
    echo: false
