name: Filecoin In Numbers

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  numbers:
    name: Filecoin In Numbers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: numbers/package-lock.json

      - name: Install DuckDB CLI
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip -O duckdb_cli.zip
          unzip duckdb_cli.zip
          chmod +x duckdb
          mv duckdb /usr/local/bin

      - name: Install dependencies
        working-directory: numbers
        run: npm ci

      - name: Build
        working-directory: numbers
        run: npm run build

      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
      #     projectName: filecoin-in-numbers
      #     directory: numbers/dist
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
